# Generated by Django 5.2.1 on 2025-05-26 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 9, 27, 27, 539330)),
        ),
    ]
