# Generated by Django 5.2.1 on 2025-05-26 14:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_author_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 14, 51, 56, 331800, tzinfo=datetime.timezone.utc)),
        ),
    ]
