# Generated by Django 5.2.1 on 2025-05-28 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_book_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published'], 'verbose_name': 'Book', 'verbose_name_plural': 'Book'},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='main/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 9, 35, 19, 430158, tzinfo=datetime.timezone.utc)),
        ),
    ]
