# Generated by Django 5.2.1 on 2025-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_customeruser_is_active_customeruser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
